name: Generate profile assets

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate_snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark


      - name: push snake.svg to the snake branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
          keep_history: true
          author: 0xSharkBoy <achille@0xsharkboy.dev>
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  generate_profile_cards:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate profile cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 2
          AUTO_PUSH: false

      - name: push cards to cards branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: cards
          build_dir: profile-summary-card-output
          keep_history: true
          author: 0xSharkBoy <achille@0xsharkboy.dev>
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
